export const CHOOSE_BIG_BURGER = 'CHOOSE_BIG_BURGER';
export const CHOOSE_SMALL_BURGER = 'CHOOSE_SMALL_BURGER';
export const CHOOSE_CHEESE = 'CHOOSE_CHEESE';
export const CHOOSE_SALAD = 'CHOOSE_SALAD';
export const CHOOSE_POTATO = 'CHOOSE_POTATO';
export const CHOOSE_SEASONING = 'CHOOSE_SEASONING';
export const CHOOSE_MAYO = 'CHOOSE_MAYO';


