export const CHOOSE_BURGER = 'CHOOSE_BURGER';
export const CHOOSE_FILLING = 'CHOOSE_FILLING';
export const CHOOSE_SUPPLEMENTS = 'CHOOSE_SUPPLEMENTS';

// export const DELETE_BURGER = 'DELETE_BURGER';
export const DELETE_FILLING = 'DELETE_FILLING';
export const DELETE_SUPPLEMENTS = 'DELETE_SUPPLEMENTS';

export const COUNT_TOTALS = 'COUNT_TOTALS';



